# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER quizmate

# 挂载目录
VOLUME /home/quizmate
# 创建目录
RUN mkdir -p /home/quizmate
# 指定路径
WORKDIR /home/quizmate
# 复制jar文件到路径
COPY ./jar/quizmate-auth.jar /home/quizmate/quizmate-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","quizmate-auth.jar"]